//! Generates the ESI client from `spec/esi-latest.json` at compile time.
//!
//! The committed spec is exactly what CCP publishes (pretty-printed); the
//! normalizations in `build_support/normalize.rs` happen in memory only and
//! are documented in `spec/README.md`.

use serde_json::Value;

include!("build_support/normalize.rs");
include!("build_support/rate_limit_window.rs");

const SPEC_PATH: &str = "spec/esi-latest.json";

/// One operation's rate-limit declaration from the spec's `x-rate-limit`
/// extension, keyed by the snake_case operation id progenitor hands to
/// `ClientHooks` at runtime.
struct RateLimitEntry {
    operation_id: String,
    group: String,
    max_tokens: u32,
    window_secs: u64,
}

fn rate_limit_table(spec: &Value) -> Vec<RateLimitEntry> {
    use heck::ToSnakeCase;

    let mut entries = Vec::new();
    let Some(paths) = spec.get("paths").and_then(Value::as_object) else {
        return entries;
    };
    for path_item in paths.values() {
        for method in SPEC_HTTP_METHODS {
            let Some(op) = path_item.get(method) else {
                continue;
            };
            let Some(limit) = op.get("x-rate-limit") else {
                continue;
            };
            let operation_id = op.get("operationId").and_then(Value::as_str);
            let group = limit.get("group").and_then(Value::as_str);
            let max_tokens = limit
                .get("max-tokens")
                .and_then(Value::as_u64)
                .and_then(|n| u32::try_from(n).ok());
            let window_secs = limit
                .get("window-size")
                .and_then(Value::as_str)
                .and_then(parse_window_size);
            match (operation_id, group, max_tokens, window_secs) {
                (Some(id), Some(group), Some(max_tokens), Some(window_secs)) => {
                    entries.push(RateLimitEntry {
                        // Same conversion progenitor applies to operationId.
                        operation_id: id.to_snake_case(),
                        group: group.to_string(),
                        max_tokens,
                        window_secs,
                    })
                }
                // Header-driven learning still covers this operation at
                // runtime; the gate just can't engage before its first call.
                _ => println!(
                    "cargo:warning=skipping unparseable x-rate-limit on {}: {limit}",
                    operation_id.unwrap_or("<no operationId>")
                ),
            }
        }
    }
    entries.sort_by(|a, b| a.operation_id.cmp(&b.operation_id));
    entries
}

fn render_rate_limit_table(entries: &[RateLimitEntry]) -> String {
    let mut out = String::from(
        "/// Rate-limit group, token budget, and window (seconds) declared for an\n\
         /// operation by the spec's `x-rate-limit` extension. Generated by build.rs.\n\
         pub(crate) fn spec_rate_limit(operation_id: &str) -> Option<(&'static str, u32, u64)> {\n\
         \x20   match operation_id {\n",
    );
    for e in entries {
        out.push_str(&format!(
            "        {:?} => Some(({:?}, {}, {})),\n",
            e.operation_id, e.group, e.max_tokens, e.window_secs
        ));
    }
    out.push_str("        _ => None,\n    }\n}\n\n");
    out.push_str(&format!(
        "/// How many operations the spec declares a rate limit for.\n\
         #[allow(dead_code)]\n\
         pub(crate) const SPEC_RATE_LIMITED_OPERATIONS: usize = {};\n",
        entries.len()
    ));
    out
}

fn main() {
    println!("cargo:rerun-if-changed={SPEC_PATH}");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=build_support/normalize.rs");
    println!("cargo:rerun-if-changed=build_support/rate_limit_window.rs");

    let file = std::fs::File::open(SPEC_PATH).expect("failed to open spec file");
    let mut raw: Value = serde_json::from_reader(file).expect("spec is not valid JSON");

    let rate_limits = rate_limit_table(&raw);
    normalize_responses(&mut raw);
    let compatibility_date = strip_compatibility_date_param(&mut raw);
    let base_url = raw
        .pointer("/servers/0/url")
        .and_then(Value::as_str)
        .expect("spec declares no server URL")
        .to_string();
    let sso_authorize_url = raw
        .pointer("/components/securitySchemes/OAuth2/flows/authorizationCode/authorizationUrl")
        .and_then(Value::as_str)
        .expect("spec declares no OAuth2 authorization URL")
        .to_string();
    let sso_token_url = raw
        .pointer("/components/securitySchemes/OAuth2/flows/authorizationCode/tokenUrl")
        .and_then(Value::as_str)
        .expect("spec declares no OAuth2 token URL")
        .to_string();

    let spec: openapiv3::OpenAPI =
        serde_json::from_value(raw).expect("spec failed to parse as OpenAPI 3.0");

    let mut settings = progenitor::GenerationSettings::default();
    settings.with_interface(progenitor::InterfaceStyle::Builder);
    settings.with_inner_type("crate::EsiInner".parse().unwrap());
    let mut generator = progenitor::Generator::new(&settings);
    let tokens = generator
        .generate_tokens(&spec)
        .expect("progenitor failed to generate client");
    let ast = syn::parse2(tokens).expect("failed to parse generated tokens");
    let mut content = prettyplease::unparse(&ast);

    content.push_str(&format!(
        "\n/// The ESI compatibility date this client was generated against.\n\
         ///\n\
         /// Sent automatically as the `X-Compatibility-Date` header on every\n\
         /// request made through [`Client`].\n\
         pub const COMPATIBILITY_DATE: &str = \"{compatibility_date}\";\n\
         \n\
         /// ESI's base URL, from the spec's `servers` entry.\n\
         pub const BASE_URL: &str = \"{base_url}\";\n\
         \n\
         /// EVE SSO authorization endpoint, from the spec's OAuth2 security scheme.\n\
         pub const SSO_AUTHORIZE_URL: &str = \"{sso_authorize_url}\";\n\
         \n\
         /// EVE SSO token endpoint, from the spec's OAuth2 security scheme.\n\
         pub const SSO_TOKEN_URL: &str = \"{sso_token_url}\";\n"
    ));

    // The rate-limit table joins on progenitor's operation ids; if the two
    // conventions ever drift apart, the gate would silently never engage.
    let unmatched: Vec<&str> = rate_limits
        .iter()
        .map(|e| e.operation_id.as_str())
        .filter(|id| !content.contains(&format!("operation_id: \"{id}\"")))
        .collect();
    if !unmatched.is_empty() {
        println!(
            "cargo:warning={} rate-limit table entries match no generated operation id: {:?}",
            unmatched.len(),
            unmatched
        );
    }

    let out_dir = std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap());
    std::fs::write(out_dir.join("codegen.rs"), content).expect("failed to write generated code");
    std::fs::write(
        out_dir.join("rate_limits.rs"),
        render_rate_limit_table(&rate_limits),
    )
    .expect("failed to write rate-limit table");
}
